cache docker builds

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -23,6 +23,9 @@ matrix:
     - php: 7.2
       env: BITCOIN_VERSION=0.15.1
 
+before_install:
+    - if [ "${COVERAGE}" = "true" ]; then ./travis/docker-load-cache.sh bitcoinconsensusbuild || echo "failed"; fi
+
 install:
     - |
         wget https://bitcoin.org/bin/bitcoin-core-${BITCOIN_VERSION}/bitcoin-${BITCOIN_VERSION}-x86_64-linux-gnu.tar.gz \
@@ -46,9 +49,14 @@ install:
     - composer update
 
 before_script:
-    - php-config || true
-    - phpenv rehash
-    - phpenv version-name
+ - php-config || true
+ - phpenv rehash
+ - phpenv version-name
+ - |
+     if [ "${COVERAGE}" = "true" ]; then \
+       cd travis/phpqa/ && docker build -t bitcoinconsensusbuild . && cd ../.. && \
+       ./travis/docker-save-cache.sh bitcoinconsensusbuild
+     fi
 
 script:
     - tools/verify_stubs.sh || exit 1
