push code coverage to codecov.io

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,10 +1,10 @@
 language: php
 
 php:
-    - 7.0
-    - 7.1
-    - 7.2
-    - nightly
+  - 7.0
+  - 7.1
+  - 7.2
+  - nightly
 
 env:
   - BITCOIN_VERSION=0.16.0
@@ -24,41 +24,44 @@ matrix:
       env: BITCOIN_VERSION=0.15.1
 
 before_install:
-    - if [ "${COVERAGE}" = "true" ]; then ./travis/docker-load-cache.sh bitcoinconsensusbuild || echo "failed"; fi
+  - if [ "${COVERAGE}" = "true" ]; then ./travis/docker-load-cache.sh bitcoinconsensusbuild || echo "failed"; fi
 
 install:
-    - |
-        wget https://bitcoin.org/bin/bitcoin-core-${BITCOIN_VERSION}/bitcoin-${BITCOIN_VERSION}-x86_64-linux-gnu.tar.gz \
-        && tar xvf bitcoin-${BITCOIN_VERSION}-x86_64-linux-gnu.tar.gz \
-        && cd bitcoin-${BITCOIN_VERSION} \
-        && sudo cp include/bitcoinconsensus.h /usr/include/ \
-        && sudo cp lib/libbitcoinconsensus.so.0.0.0 /usr/lib/ \
-        && sudo ln /usr/lib/libbitcoinconsensus.so.0.0.0 -s /usr/lib/libbitcoinconsensus.so.0 \
-        && sudo ln /usr/lib/libbitcoinconsensus.so.0.0.0 -s /usr/lib/libbitcoinconsensus.so \
-        && sudo ls -lsah /usr/lib/libbitcoin* \
-        && sudo ldconfig \
-        && cd ..
-    - |
-        cd bitcoinconsensus \
-        && phpize && ./configure --with-bitcoinconsensus && make && sudo make install \
-        && cd ..
-    - |
-        cp bitcoin-${BITCOIN_VERSION}/lib/libbitcoinconsensus.so.0.0.0 tools/phpqa/lib/ && \
-        cp bitcoin-${BITCOIN_VERSION}/include/bitcoinconsensus.h tools/phpqa/lib/
-    - git clone https://github.com/jonasnick/bitcoinconsensus_testcases.git
-    - composer update
+  - |
+      wget https://bitcoin.org/bin/bitcoin-core-${BITCOIN_VERSION}/bitcoin-${BITCOIN_VERSION}-x86_64-linux-gnu.tar.gz \
+      && tar xvf bitcoin-${BITCOIN_VERSION}-x86_64-linux-gnu.tar.gz \
+      && cd bitcoin-${BITCOIN_VERSION} \
+      && sudo cp include/bitcoinconsensus.h /usr/include/ \
+      && sudo cp lib/libbitcoinconsensus.so.0.0.0 /usr/lib/ \
+      && sudo ln /usr/lib/libbitcoinconsensus.so.0.0.0 -s /usr/lib/libbitcoinconsensus.so.0 \
+      && sudo ln /usr/lib/libbitcoinconsensus.so.0.0.0 -s /usr/lib/libbitcoinconsensus.so \
+      && sudo ls -lsah /usr/lib/libbitcoin* \
+      && sudo ldconfig \
+      && cd ..
+  - |
+      cd bitcoinconsensus \
+      && phpize && ./configure --with-bitcoinconsensus && make && sudo make install \
+      && cd ..
+  - |
+      cp bitcoin-${BITCOIN_VERSION}/lib/libbitcoinconsensus.so.0.0.0 tools/phpqa/lib/ && \
+      cp bitcoin-${BITCOIN_VERSION}/include/bitcoinconsensus.h tools/phpqa/lib/
+  - git clone https://github.com/jonasnick/bitcoinconsensus_testcases.git
+  - composer update
 
 before_script:
- - php-config || true
- - phpenv rehash
- - phpenv version-name
- - |
-     if [ "${COVERAGE}" = "true" ]; then \
-       cd travis/phpqa/ && docker build -t bitcoinconsensusbuild . && cd ../.. && \
-       ./travis/docker-save-cache.sh bitcoinconsensusbuild
-     fi
+  - php-config || true
+  - phpenv rehash
+  - phpenv version-name
+  - |
+      if [ "${COVERAGE}" = "true" ]; then \
+        cd tools/phpqa/ && docker build -t bitcoinconsensusbuild . && cd ../.. && \
+        ./tools/docker-save-cache.sh bitcoinconsensusbuild
+      fi
 
 script:
-    - tools/verify_stubs.sh || exit 1
-    - php -dextension=bitcoinconsensus.so vendor/bin/phpunit --debug tests/
-    - tools/run_coverage_test.sh || exit 1
+  - tools/verify_stubs.sh || exit 1
+  - php -dextension=bitcoinconsensus.so vendor/bin/phpunit --debug tests/
+  - tools/run_coverage_test.sh || exit 1
+
+after_script:
+  - bash <(curl -s https://codecov.io/bash)
